vra_raw_schema = {
    "icao_airline_code": "string",
    "airline_name": "string",
    "flight_number": "string",
    "di_code": "string",
    "line_type_code": "string",
    "aircraft_model": "string",
    "seat_count": "bigint",
    "origin_airport_icao": "string",
    "origin_airport_name": "string",
    "scheduled_departure": "string",
    "actual_departure": "string",
    "destination_airport_icao": "string",
    "destination_airport_name": "string",
    "scheduled_arrival": "string",
    "actual_arrival": "string",
    "flight_status": "string",
    "justification": "double",
    "reference": "timestamp",
    "departure_status": "string",
    "arrival_status": "string",
    "year": "string",
    "month": "string"
}

vra_columns_name_remap = {
    'Sigla ICAO Empresa Aérea': 'icao_airline_code',
    'Empresa Aérea': 'airline_name',
    'Número Voo': 'flight_number',
    'Código DI': 'di_code',
    'Código Tipo Linha': 'line_type_code',
    'Modelo Equipamento': 'aircraft_model',
    'Número de Assentos': 'seat_count',
    'Sigla ICAO Aeroporto Origem': 'origin_airport_icao',
    'Descrição Aeroporto Origem': 'origin_airport_name',
    'Partida Prevista': 'scheduled_departure',
    'Partida Real': 'actual_departure',
    'Sigla ICAO Aeroporto Destino': 'destination_airport_icao',
    'Descrição Aeroporto Destino': 'destination_airport_name',
    'Chegada Prevista': 'scheduled_arrival',
    'Chegada Real': 'actual_arrival',
    'Situação Voo': 'flight_status',
    'Justificativa': 'justification',
    'Referência': 'reference',
    'Situação Partida': 'departure_status',
    'Situação Chegada': 'arrival_status',
}